#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InventarioDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_cache_proveedor(tbl_cache_proveedor instance);
    partial void Updatetbl_cache_proveedor(tbl_cache_proveedor instance);
    partial void Deletetbl_cache_proveedor(tbl_cache_proveedor instance);
    partial void Inserttbl_imagen_producto(tbl_imagen_producto instance);
    partial void Updatetbl_imagen_producto(tbl_imagen_producto instance);
    partial void Deletetbl_imagen_producto(tbl_imagen_producto instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos.Properties.Settings.Default.InventarioDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_cache_proveedor> tbl_cache_proveedor
		{
			get
			{
				return this.GetTable<tbl_cache_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_imagen_producto> tbl_imagen_producto
		{
			get
			{
				return this.GetTable<tbl_imagen_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cache_proveedor")]
	public partial class tbl_cache_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cache;
		
		private int _id_prov_eliminado;
		
		private System.Nullable<System.DateTime> _fecha_eliminacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cacheChanging(int value);
    partial void Onid_cacheChanged();
    partial void Onid_prov_eliminadoChanging(int value);
    partial void Onid_prov_eliminadoChanged();
    partial void Onfecha_eliminacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_eliminacionChanged();
    #endregion
		
		public tbl_cache_proveedor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cache", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cache
		{
			get
			{
				return this._id_cache;
			}
			set
			{
				if ((this._id_cache != value))
				{
					this.Onid_cacheChanging(value);
					this.SendPropertyChanging();
					this._id_cache = value;
					this.SendPropertyChanged("id_cache");
					this.Onid_cacheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prov_eliminado", DbType="Int NOT NULL")]
		public int id_prov_eliminado
		{
			get
			{
				return this._id_prov_eliminado;
			}
			set
			{
				if ((this._id_prov_eliminado != value))
				{
					this.Onid_prov_eliminadoChanging(value);
					this.SendPropertyChanging();
					this._id_prov_eliminado = value;
					this.SendPropertyChanged("id_prov_eliminado");
					this.Onid_prov_eliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_eliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_eliminacion
		{
			get
			{
				return this._fecha_eliminacion;
			}
			set
			{
				if ((this._fecha_eliminacion != value))
				{
					this.Onfecha_eliminacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_eliminacion = value;
					this.SendPropertyChanged("fecha_eliminacion");
					this.Onfecha_eliminacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_imagen_producto")]
	public partial class tbl_imagen_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_img;
		
		private int _id_pro;
		
		private string _ruta_img;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_imgChanging(int value);
    partial void Onid_imgChanged();
    partial void Onid_proChanging(int value);
    partial void Onid_proChanged();
    partial void Onruta_imgChanging(string value);
    partial void Onruta_imgChanged();
    #endregion
		
		public tbl_imagen_producto()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_img", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_img
		{
			get
			{
				return this._id_img;
			}
			set
			{
				if ((this._id_img != value))
				{
					this.Onid_imgChanging(value);
					this.SendPropertyChanging();
					this._id_img = value;
					this.SendPropertyChanged("id_img");
					this.Onid_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", DbType="Int NOT NULL")]
		public int id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruta_img", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ruta_img
		{
			get
			{
				return this._ruta_img;
			}
			set
			{
				if ((this._ruta_img != value))
				{
					this.Onruta_imgChanging(value);
					this.SendPropertyChanging();
					this._ruta_img = value;
					this.SendPropertyChanged("ruta_img");
					this.Onruta_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_imagen_producto", Storage="_tbl_producto", ThisKey="id_pro", OtherKey="id_pro", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_imagen_producto.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_imagen_producto.Add(this);
						this._id_pro = value.id_pro;
					}
					else
					{
						this._id_pro = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pro;
		
		private System.Nullable<int> _id_prov;
		
		private string _nombre_pro;
		
		private string _categoria_pro;
		
		private decimal _precio_pro;
		
		private string _ruta_imagen_pro;
		
		private EntitySet<tbl_imagen_producto> _tbl_imagen_producto;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proChanging(int value);
    partial void Onid_proChanged();
    partial void Onid_provChanging(System.Nullable<int> value);
    partial void Onid_provChanged();
    partial void Onnombre_proChanging(string value);
    partial void Onnombre_proChanged();
    partial void Oncategoria_proChanging(string value);
    partial void Oncategoria_proChanged();
    partial void Onprecio_proChanging(decimal value);
    partial void Onprecio_proChanged();
    partial void Onruta_imagen_proChanging(string value);
    partial void Onruta_imagen_proChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_imagen_producto = new EntitySet<tbl_imagen_producto>(new Action<tbl_imagen_producto>(this.attach_tbl_imagen_producto), new Action<tbl_imagen_producto>(this.detach_tbl_imagen_producto));
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pro
		{
			get
			{
				return this._id_pro;
			}
			set
			{
				if ((this._id_pro != value))
				{
					this.Onid_proChanging(value);
					this.SendPropertyChanging();
					this._id_pro = value;
					this.SendPropertyChanged("id_pro");
					this.Onid_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prov", DbType="Int")]
		public System.Nullable<int> id_prov
		{
			get
			{
				return this._id_prov;
			}
			set
			{
				if ((this._id_prov != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_provChanging(value);
					this.SendPropertyChanging();
					this._id_prov = value;
					this.SendPropertyChanged("id_prov");
					this.Onid_provChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_pro", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_pro
		{
			get
			{
				return this._nombre_pro;
			}
			set
			{
				if ((this._nombre_pro != value))
				{
					this.Onnombre_proChanging(value);
					this.SendPropertyChanging();
					this._nombre_pro = value;
					this.SendPropertyChanged("nombre_pro");
					this.Onnombre_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria_pro", DbType="NVarChar(50)")]
		public string categoria_pro
		{
			get
			{
				return this._categoria_pro;
			}
			set
			{
				if ((this._categoria_pro != value))
				{
					this.Oncategoria_proChanging(value);
					this.SendPropertyChanging();
					this._categoria_pro = value;
					this.SendPropertyChanged("categoria_pro");
					this.Oncategoria_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_pro", DbType="Decimal(18,2) NOT NULL")]
		public decimal precio_pro
		{
			get
			{
				return this._precio_pro;
			}
			set
			{
				if ((this._precio_pro != value))
				{
					this.Onprecio_proChanging(value);
					this.SendPropertyChanging();
					this._precio_pro = value;
					this.SendPropertyChanged("precio_pro");
					this.Onprecio_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruta_imagen_pro", DbType="VarChar(MAX)")]
		public string ruta_imagen_pro
		{
			get
			{
				return this._ruta_imagen_pro;
			}
			set
			{
				if ((this._ruta_imagen_pro != value))
				{
					this.Onruta_imagen_proChanging(value);
					this.SendPropertyChanging();
					this._ruta_imagen_pro = value;
					this.SendPropertyChanged("ruta_imagen_pro");
					this.Onruta_imagen_proChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_imagen_producto", Storage="_tbl_imagen_producto", ThisKey="id_pro", OtherKey="id_pro")]
		public EntitySet<tbl_imagen_producto> tbl_imagen_producto
		{
			get
			{
				return this._tbl_imagen_producto;
			}
			set
			{
				this._tbl_imagen_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="id_prov", OtherKey="id_prov", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._id_prov = value.id_prov;
					}
					else
					{
						this._id_prov = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_imagen_producto(tbl_imagen_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_imagen_producto(tbl_imagen_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_prov;
		
		private string _nombre_prov;
		
		private string _ruc_prov;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_provChanging(int value);
    partial void Onid_provChanged();
    partial void Onnombre_provChanging(string value);
    partial void Onnombre_provChanged();
    partial void Onruc_provChanging(string value);
    partial void Onruc_provChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prov", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_prov
		{
			get
			{
				return this._id_prov;
			}
			set
			{
				if ((this._id_prov != value))
				{
					this.Onid_provChanging(value);
					this.SendPropertyChanging();
					this._id_prov = value;
					this.SendPropertyChanged("id_prov");
					this.Onid_provChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_prov", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre_prov
		{
			get
			{
				return this._nombre_prov;
			}
			set
			{
				if ((this._nombre_prov != value))
				{
					this.Onnombre_provChanging(value);
					this.SendPropertyChanging();
					this._nombre_prov = value;
					this.SendPropertyChanged("nombre_prov");
					this.Onnombre_provChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc_prov", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ruc_prov
		{
			get
			{
				return this._ruc_prov;
			}
			set
			{
				if ((this._ruc_prov != value))
				{
					this.Onruc_provChanging(value);
					this.SendPropertyChanging();
					this._ruc_prov = value;
					this.SendPropertyChanged("ruc_prov");
					this.Onruc_provChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="id_prov", OtherKey="id_prov")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _correo_usu;
		
		private string _clave_usu;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Oncorreo_usuChanging(string value);
    partial void Oncorreo_usuChanged();
    partial void Onclave_usuChanging(string value);
    partial void Onclave_usuChanged();
    #endregion
		
		public tbl_usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_usu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_usu
		{
			get
			{
				return this._correo_usu;
			}
			set
			{
				if ((this._correo_usu != value))
				{
					this.Oncorreo_usuChanging(value);
					this.SendPropertyChanging();
					this._correo_usu = value;
					this.SendPropertyChanged("correo_usu");
					this.Oncorreo_usuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave_usu", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string clave_usu
		{
			get
			{
				return this._clave_usu;
			}
			set
			{
				if ((this._clave_usu != value))
				{
					this.Onclave_usuChanging(value);
					this.SendPropertyChanging();
					this._clave_usu = value;
					this.SendPropertyChanged("clave_usu");
					this.Onclave_usuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
